name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # Add all plugins in use
      - run: pip install mkdocs-material
      
      # deploy the website to the gh-pages branch
      - run: mkdocs gh-deploy --force
